### ISSUE TITLE
算法原理

### ISSUE THREAD

**Issue by baif666** [ladingwu/-#1]
代码逻辑很清楚，但是算法的原理是啥啊？另外如果想继续研究有什么推荐资料吗？

**Comment by ladingwu** [comment]
你是想深入学习图像识别还是验证码识别啊？

**Comment by baif666** [comment]
图像识别吧

**Comment by ladingwu** [comment]
如果是识别的话，那可以学习机器学习和深度学习，这都是比较难的。。入门推荐台大的《机器学习基石》

**Comment by baif666** [comment]
好的，谢谢

**Comment by DreamClimb** [comment]
图文混排的不支持么？？链接打不开呀。。

**Comment by ladingwu** [comment]
时间太久了，可能原来的普通验证码链接已经失效了
